[package]
name = "term_present"
version = "0.1.0"
authors = ["David Hamp-Gonsalves <davidhampgonsalves@gmail.com>"]

[dependencies]
pulldown-cmark = { git = "https://github.com/davidhampgonsalves/pulldown-cmark.git", rev = "0966192" }
termion        = "1.0.8"
syntect        = "1.0"
